AWSTemplateFormatVersion: "2010-09-09"

Description: >-
                This is a nested stack that creates a EC2 instance in a VPC with public and private subnets

Resources:
    VPCStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./vpc/vpc.yml

    NATGatewayStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./nat_gateway/nat_gateway.yml
            Parameters:
                PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
                PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2

    RouteTableStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./route_tables/route_tables.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VpcId
                VpcName: !GetAtt VPCStack.Outputs.VpcName
                PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
                PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
                NATGateway1: !GetAtt NATGatewayStack.Outputs.NATGateway1
                NATGateway2: !GetAtt NATGatewayStack.Outputs.NATGateway2
                PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
                PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2

    SecurityGroupStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./security_groups/security_groups.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VpcId

    EC2Instance:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./ec2/ec2.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VpcId
                PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
                PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
                PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
                PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
                PublicEC2SG: !GetAtt SecurityGroupStack.Outputs.PublicEC2SG
                PrivateEC2SG: !GetAtt SecurityGroupStack.Outputs.PrivateEC2SG
