AWSTemplateFormatVersion: "2010-09-09"

Description: >-
                This is a nested stack that creates a EC2 instance in a VPC with public and private subnets

Parameters:
    BucketName:
        Description: The name of the S3 bucket
        Type: String
        Default: group03-s3-bucket

Resources:
    # S3Bucket:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/s3.yml
    #         Parameters:
    #             BucketName: !Ref BucketName

    VPCStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/vpc.yml

    NATGatewayStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/nat_gateway.yml
            Parameters:
                PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
                PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2

    RouteTableStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/route_tables.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VpcId
                VpcName: !GetAtt VPCStack.Outputs.VpcName
                PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
                PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
                NATGateway1: !GetAtt NATGatewayStack.Outputs.NATGateway1
                NATGateway2: !GetAtt NATGatewayStack.Outputs.NATGateway2
                PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
                PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2

    SecurityGroupStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/security_groups.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VpcId

    EC2Instance:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: !Sub https://s3.amazonaws.com/${BucketName}/ec2.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VpcId
                PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
                PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
                PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
                PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
                PublicEC2SG: !GetAtt SecurityGroupStack.Outputs.PublicEC2SG
                PrivateEC2SG: !GetAtt SecurityGroupStack.Outputs.PrivateEC2SG

Outputs:
    EC2Instance:
        Description: The ID of the EC2 instance
        Value: !GetAtt EC2Instance.Outputs.EC2Instance
        Export:
            Name: !Sub ${AWS::Region}-${AWS::StackName}-EC2Instance