AWSTemplateFormatVersion: "2010-09-09"

Description: >-
                This is a nested stack that creates a EC2 instance in a VPC with public and private subnets

Resources:
    VPCStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./vpc/vpc_stack.yml

    RouteTableStack:
        Type: AWS::CloudFormation::Stack
        Properties:
            TemplateURL: ./route_table/route_table_stack.yml
            Parameters:
                VpcId: !GetAtt VPCStack.Outputs.VPCId
        DependsOn:
             - VPCStack

    # NATGatewayStack:
    #     Type: AWS::CloudFormation::Stack
    #     Properties:
    #         TemplateURL: ./nat_gateway/nat_gateway.yml
    #         Parameters:
    #             VpcId: !GetAtt VPCStack.Outputs.VPCId
                